### ISSUE TITLE
No values supplied by Gin or caller for arguments during pre-extract-feature.sh execution

### ISSUE THREAD

**Issue by brenowca** [liulu112601/URT#3]
Hi there!

I am trying to run the feature dump script (it is not easy for me to download such large folders from google drive in the cluster I run my experiments for now), but I am getting this missing-argument error message below.

Could you guide me on which values should I use for `ignore_hierarchy_probability`and `simclr_episode_fraction`. Oh, and can you show me as well how I insert them?

By the way, I loved your paper.

Thanks in advance for your time :)

```
2021-09-15 12:14:12.036526: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
[2021-09-15 04:14:23 PM] --- args ---
  [save_dir  ] : features_cache
  [model.backbone] : resnet18
  [model.classifier] : cosine
  [train.max_iter] : 10000
  [eval.max_iter] : 600
[2021-09-15 04:14:23 PM] --- args ---
Traceback (most recent call last):
  File "exps/pre-extract-feature.py", line 144, in <module>
    main(xargs)
  File "exps/pre-extract-feature.py", line 91, in main
    train_loader_lst  = [MetaDatasetEpisodeReader('train', [d], [d], all_test_datasets) for d in extractor_domains]
  File "exps/pre-extract-feature.py", line 91, in <listcomp>
    train_loader_lst  = [MetaDatasetEpisodeReader('train', [d], [d], all_test_datasets) for d in extractor_domains]
  File "/dccstor/kcsys/brenow/utils/URT/fast-exps/lib/data/meta_dataset_reader.py", line 110, in __init__
    train_episode_desscription = config.EpisodeDescriptionConfig(None, None, None)
  File "/u/brenow1/miniconda3/envs/neurips_2021/lib/python3.8/site-packages/gin/config.py", line 1069, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/u/brenow1/miniconda3/envs/neurips_2021/lib/python3.8/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/u/brenow1/miniconda3/envs/neurips_2021/lib/python3.8/site-packages/gin/config.py", line 1046, in gin_wrapper
    return fn(*new_args, **new_kwargs)
TypeError: __init__() missing 2 required positional arguments: 'ignore_hierarchy_probability' and 'simclr_episode_fraction'
  No values supplied by Gin or caller for arguments: ['ignore_hierarchy_probability', 'simclr_episode_fraction']
  Gin had values bound for: ['ignore_bilevel_ontology', 'ignore_dag_ontology', 'max_log_weight', 'max_num_query', 'max_support_set_size', 'max_support_size_contrib_per_class', 'max_ways_upper_bound', 'min_log_weight', 'min_ways']
  Caller supplied values for: ['num_query', 'num_support', 'num_ways', 'self']
  In call to configurable 'EpisodeDescriptionConfig' (<class 'meta_dataset.data.config.EpisodeDescriptionConfig'>)
  ```

**Comment by thamycoelho** [comment]
I am having the same issue, @brenowca could you solve it?

**Comment by HongduanTian** [comment]
I have the same issue as well.
